#!/bin/bash

cd /cromwell_root
tmpDir=$(mkdir -p "/cromwell_root/tmp.095ee658" && echo "/cromwell_root/tmp.095ee658")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell_root
touch /cromwell_root/monitoring.log
chmod u+x /cromwell_root/monitoring.sh
/cromwell_root/monitoring.sh > /cromwell_root/monitoring.log &
)
out35f429b3="${tmpDir}/out.$$" err35f429b3="${tmpDir}/err.$$"
mkfifo "$out35f429b3" "$err35f429b3"
trap 'rm "$out35f429b3" "$err35f429b3"' EXIT
tee '/cromwell_root/stdout' < "$out35f429b3" &
tee '/cromwell_root/stderr' < "$err35f429b3" >&2 &
(
cd /cromwell_root


mkdir tmp
export TMPDIR="${PWD}/tmp"
export SEGWAY_RAND_SEED=112344321
export SEGWAY_NUM_LOCAL_JOBS=96
export OMP_NUM_THREADS=1
mkdir traindir && tar xf /cromwell_root/segway-testing/segway/35f429b3-1726-4e57-b181-ea87e6c73277/call-segway_train/traindir.tar.gz -C traindir --strip-components 1
mkdir identifydir
SEGWAY_CLUSTER=local segway annotate /cromwell_root/segway-testing/segway/35f429b3-1726-4e57-b181-ea87e6c73277/call-make_genomedata/files.genomedata --bed=segway.bed traindir identifydir
find traindir -regextype egrep -regex 'traindir/(auxiliary|params/input.master|params/params.params|segway.str|triangulation)($|/.*)' -print0 |
    LC_ALL=C sort -z |
    tar --owner=0 --group=0 --numeric-owner --mtime='2019-01-01 00:00Z' \
    --pax-option=exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime \
    --no-recursion --null -T - -cf training_params.tar
gzip -nc training_params.tar > training_params.tar.gz
gzip -nc segway.bed > segway.bed.gz
)  > "$out35f429b3" 2> "$err35f429b3"
echo $? > /cromwell_root/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell_root
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell_root
sync
# make the directory which will keep the matching files
mkdir /cromwell_root/glob-e59fb0efcac8bc0ed00369eb031c972e

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell_root/glob-e59fb0efcac8bc0ed00369eb031c972e/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /cromwell_root/identifydir/output/e/identify/* /cromwell_root/glob-e59fb0efcac8bc0ed00369eb031c972e 2> /dev/null ) || ( ln /cromwell_root/identifydir/output/e/identify/* /cromwell_root/glob-e59fb0efcac8bc0ed00369eb031c972e )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell_root/glob-e59fb0efcac8bc0ed00369eb031c972e | grep -v cromwell_glob_control_file > /cromwell_root/glob-e59fb0efcac8bc0ed00369eb031c972e.list


)
mv /cromwell_root/rc.tmp /cromwell_root/rc
